### ISSUE TITLE
subscribe / unsubscribe v5

### ISSUE THREAD

**Issue by huevent** [tiagosiebler/bybit-api#292] opened 2023-10-28 19:57 UTC
Hello. I would like to be able to subscribe and unsubscribe from topics as needed, but
unsubscribeV5(['tickers.BTCUSDT'], 'spot')
unsubscribes from everything at once. How can I unsubscribe from only some subscriptions and keep the ones I need? I tried to understand your documentation, but so far without success.

**Comment by tiagosiebler** [comment] 2023-10-30 12:03
Hi @huevent 

Are you on the latest version? I've just done a quick test and I can't reproduce this issue. I've also enabled the "silly" logger level (I'll provide an example below), so I can monitor what "unsubscribe" event is being sent to the server, and I can see it only unsubscribes the topics I ask it to. Here's how I tested it:

```typescript
import { DefaultLogger, WebsocketClient } from 'bybit-api';

// Override the logger to enable the "silly" level
const logger = {
  ...DefaultLogger,
  silly: (...params) => console.log('silly', ...params),
};


const wsClient = new WebsocketClient(
  {
    market: 'v5',
  },
  logger,
);

wsClient.on('update', (data) => {
  console.log('raw message received ', JSON.stringify(data));
});

wsClient.on('open', (data) => {
  console.log('connection opened open:', data.wsKey);
});
wsClient.on('response', (data) => {
  console.log('log response: ', JSON.stringify(data, null, 2));
});
wsClient.on('reconnect', ({ wsKey }) => {
  console.log('ws automatically reconnecting.... ', wsKey);
});
wsClient.on('reconnected', (data) => {
  console.log('ws has reconnected ', data?.wsKey);
});


const topics = ['kline.5.XRPUSDT', 'kline.5.BTCUSDT', 'kline.5.ETHUSDT'];
wsClient.subscribeV5(topics, 'spot');

// Unsubscribe from one topic after 5 seconds:
setTimeout(() => {
  console.log('unsubscribing');
  wsClient.unsubscribeV5('kline.5.ETHUSDT', 'spot');
}, 5 * 1000);


```


Seems OK to me. When first subscribing, I receive events for all 3 symbols. When the timeout sends the unsubscribe, I see the event for only that symbol going to the server in the logs:
```typescript
silly Sending upstream ws message:  {
  category: 'bybit-ws',
  wsMessage: '{"op":"unsubscribe","args":["kline.5.ETHUSDT"]}',
  wsKey: 'v5SpotPublic'
}
log response:  {
  "success": true,
  "ret_msg": "unsubscribe",
  "conn_id": "f49980c9-6386-41f4-a426-2fcbb40f2bb5",
  "op": "unsubscribe",
  "wsKey": "v5SpotPublic"
}
```

After that, I stop receiving events for ETH but keep getting events for BTC + XRP. If you still see this issue, can you make a simple example demonstrating your problem?

**Comment by huevent** [comment] 2023-10-30 17:09
Thank you. The solution turned out to be to tear down the old package and install the new version. Now everything works. I am also grateful to you for some log code. I didn’t know that it existed and I had to write my own simple logger.
In case you're wondering, this module was causing the problem:

```const { ws } = require('./ws_bybit');

const prefix = 'tickers.';

async function subscribe(symbols, market = 'spot') {
    const order = [];
    if(Array.isArray(symbols)) {
        symbols.forEach(item => {
            order.push(prefix + item);
        });
    } else {
        order.push(prefix + symbols);
    }
    try {
    await ws.subscribeV5(order, market);
    } catch(err) {
        console.error(err.name, '\n', err.message);
    }
};

async function unsubscribe(symbols, market = 'spot') {
    const order = [];
    if(Array.isArray(symbols)) {
        symbols.forEach(item => {
            order.push(prefix + item);
        });
    } else {
        order.push(prefix + symbols);
    }
    try {
     ws.unsubscribeV5(order, market);
    } catch(err) {
        console.log(err.name, '\n', err.message);
    }
};


//subscribe('BTCUSDT');

module.exports = { subscribe, unsubscribe }```

**Comment by tiagosiebler** [comment] 2023-12-22 10:41
Glad to hear it! And thanks for sharing the snippet. Closing this for now.

**Closed as completed by tiagosiebler** 2023-12-22 10:41 UTC
Labels: user error
