### ISSUE TITLE
Error sign response on simultaneous submit & query

### ISSUE THREAD

**Issue by azidyn** [tiagosiebler/bybit-api#240] opened 2023-03-21 11:36 UTC
If I query order A `.getActiveOrders()` while submitting order B `.submitOrder()` I get an "error sign!" response from Bybit.

order A is an existing order (filled market order)
order B is a new limit order

n.b. I request both simultaneously and collect the promises with `Promise.all()`

It works correctly if I place a 500ms delay between the requests.

This is using v5 on the BTCUSD (inverse perp)

Not sure if a bybit issue or some internal state conflict in your package. 

Cheers

**Comment by tiagosiebler** [comment] 2023-03-21 11:52
Interesting, I will try to reproduce this on my end. Hard to imagine a state conflict here because the request building & signature workflow largely involves pure functions. The only local state here (such as api keys) is static, nothing dynamic comes to mind that could cause one request to lead to the failure of another. Either way, will try to reproduce and go from there.

**Comment by azidyn** [comment] 2023-03-21 11:59
Great, yeah that's what I imagined. Quite possible it's a bybit bug. 
Btw - if I `await` each request it works perfectly. Very odd! 
cheers.

**Comment by tiagosiebler** [comment] 2023-03-21 12:00
Very odd indeed! Surprisingly easily reproducible:
```typescript
    const activeOrdersReq1 = client.getActiveOrders({
      category: 'inverse',
      symbol: 'BTCUSD',
    });

    const activeOrdersReq2 = client.getActiveOrders({
      category: 'inverse',
      symbol: 'ETHUSD',
    });

    console.log(
      'responses:',
      await Promise.all([activeOrdersReq1, activeOrdersReq2])
    );
```

At least now I have everything I need to investigate, with bybit if needed. I'll look into this to figure out what's going on.

**Comment by tiagosiebler** [comment] 2023-03-21 12:25
Ah pointer mutations strike once again. When building requests and setting the headers to use, it was unintentionally mutating a pointer to the global request options shared across all requests (thus mutating the request object about to be used in a parallel request, rather than being unique & isolated per request). Would only be visible in requests firing off in parallel but definitely a problem - good catch & thank you for raising it! Surprised it hasn't been raised sooner.

Fix will be released shortly in v3.5.3, via PR #241. Tests have already passed so release will be on npm shortly once the full CI/CD run finishes.

**Closed as completed** 2023-03-21 12:26 UTC
Labels: bug

**Comment by tiagosiebler** [comment] 2023-03-21 12:28
Release complete, please try again with the latest version. Should be fixed now. If you notice anything else, please let me know - thanks!

**Comment by azidyn** [comment] 2023-03-21 12:36
Confirmed fixed, outstanding!
